name: flutter_storage_provider
description: Simple universal storage provider for many types of storage for Flutter & Flutter Web
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  sembast: ^2.4.2
  shared_preferences: ^0.5.7
  shared_preferences_web: ^0.1.2+4
  sembast_web: ^1.1.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
